config/routes.rb
Rails.application.routes.draw do
  resources :properties do
  end
  resources :landlords, shallow: true
  resources :tenants, shallow: true

  root 'welcome#index'
  get 'tenants' => 'tenants#show'
  get 'dashboard' => 'admin#dashboard'
  get 'admin/form' => 'admin#form', :as => :form

end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
	has_many :properties
end

app/models/property.rb
class Property < ActiveRecord::Base
	geocoded_by :address
	before_validation :geocode, :if => :address_changed?

	belongs_to :landlord
	has_one :tenant
	
	validates :latitude, :longitude, :landlord, presence: true
	accepts_nested_attributes_for :landlord, :tenant
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
	belongs_to :property
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
  	@property_count = Property.count
  	@property_jan_feb = Property.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_action :set_landlord, only: [:show, :edit, :update, :destroy]

  # GET /landlords
  # GET /landlords.json
  def index
    @landlords = Landlord.all
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
  end

  # GET /landlords/new
  def new
    @landlord = Landlord.new
  end

  # GET /landlords/1/edit
  def edit
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(landlord_params)

    respond_to do |format|
      if @landlord.save
        format.html { redirect_to @landlord, notice: 'Landlord was successfully created.' }
        format.json { render :show, status: :created, location: @landlord }
      else
        format.html { render :new }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landlords/1
  # PATCH/PUT /landlords/1.json
  def update
    respond_to do |format|
      if @landlord.update(landlord_params)
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { render :show, status: :ok, location: @landlord }
      else
        format.html { render :edit }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
    @landlord.destroy
    respond_to do |format|
      format.html { redirect_to landlords_url, notice: 'Landlord was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landlord
      @landlord = Landlord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landlord_params
      params.require(:landlord).permit(:first_name, :last_name, :telephone_number, :email_address, :mailing_address, :date_registered_with_us)
    end
end

app/controllers/listtype_controller.rb
class ListtypeController < ApplicationController
	def displaylist
	end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
    
    # @properties.each do
    #   property.landlord
    # end  
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])
    @property_marker = Gmaps4rails.build_markers(@property) do |prop, marker|
      marker.lat prop.latitude
      marker.lng prop.longitude
      marker.infowindow prop.address
    end
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    puts property_params
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:address, :work_outstanding, :work_outstanding_type, :latitude, :longitude, :landlord_id)
    end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]

  # GET /tenants
  # GET /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1
  # GET /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants
  # POST /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to @tenant, notice: 'Tenant was successfully created.' }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1
  # PATCH/PUT /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: 'Tenant was successfully updated.' }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1
  # DELETE /tenants/1.json
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: 'Tenant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tenant_params
      params.require(:tenant).permit(:first_name, :last_name, :telephone_number, :email_address, :date_of_commencement, :date_of_termination)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @landlords = Landlord.all
  	@properties = Property.all
  	@properties_with_outstanding_work = Property.where(work_outstanding: true)
    puts @properties
    @all_property_markers = Gmaps4rails.build_markers(@properties) do |property, marker|
      puts property.latitude
      marker.lat property.latitude
      marker.lng property.longitude
      marker.infowindow property.address
    puts @all_property_markers
    end
  end
  def worklist
  	@properties = Property.all
  	@type = Property.where(work_outstanding: true).pluck(:work_outstanding_type).pop
  	@list = Property.where(work_outstanding_type: @type)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/helpers/listtype_helper.rb
module ListtypeHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dashboard.html.erb
 <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js' %>
 <%= javascript_include_tag  '//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js' %>
<title>Dashboard</title>
<%= stylesheet_link_tag "//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css" %>

<div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">Property Pilot Dashboard</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
<div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-share-square fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Add Property</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
<div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-smile-o fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Add Landlord</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
<div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-users fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Add Tenant</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
<div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-wrench fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">Add Job</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>

<div class="col-md-3">
</div>
<div class="col-lg-6">
    <div class="panel panel-default">
        <div class class="panel-heading" id="chart-header">
            <p id="chart-title"><i class="fa fa-bar-chart-o fa-fw"></i>Branch Performance</p>
            <div id="performance-chart"></div>
        </div>
    </div>
</div>
<div class="col-md-3">
</div>

<script type="text/javascript">
        new Morris.Line({
          // ID of the element in which to draw the chart.
          element: 'performance-chart',
          // Chart data records -- each entry in this array corresponds to a point on
          // the chart.
          data: [
            { month: '2014-02', value: <%= @property_count %> },
            { month: '2014-04', value: 15 },
            { month: '2014-06', value: 20 },
            { month: '2014-08', value: 23 },
            { month: '2014-10', value: 38 }
          ],
          // The name of the data record attribute that contains x-values.
          xkey: 'month',
          // A list of names of data record attributes that contain y-values.
          ykeys: ['value'],
          // Labels for the ykeys -- will be displayed when you hover over the
          // chart.
          labels: ['Properties Managed']
        });
</script>

 <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js' %>
 <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js' %>
 <%= javascript_include_tag  '//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js' %>

app/views/admin/form.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    **here comes whatever you want to show!**
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>

app/views/admin/form.js.erb
$("#modal-window1").html("something");

app/views/landlords/edit.html.erb
<h1>Editing landlord</h1>

<%= render 'form' %>

<%= link_to 'Show', @landlord %> |
<%= link_to 'Back', landlords_path %>

app/views/landlords/index.html.erb
<%stylesheet_link_tag 'landlords.css.scss'%>
<h1>Landlords Admin Panel</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Telephone number</th>
      <th>Email address</th>
      <th>Mailing address</th>
      <th>Date registered with us</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @landlords.each do |landlord| %>
      <tr>
        <td><%= landlord.first_name %></td>
        <td><%= landlord.last_name %></td>
        <td><%= landlord.telephone_number %></td>
        <td><%= landlord.email_address %></td>
        <td><%= landlord.mailing_address %></td>
        <td><%= landlord.date_registered_with_us %></td>
        <td><%= link_to 'Show', landlord %></td>
        <td><%= link_to 'Edit', edit_landlord_path(landlord) %></td>
        <td><%= link_to 'Destroy', landlord, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Landlord', new_landlord_path %>

app/views/landlords/new.html.erb
<%= stylesheet_link_tag 'form.css.scss' %>
<h1>New Landlord</h1>



<%= render 'form' %>

<%= link_to 'Back', landlords_path %>

app/views/landlords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @landlord.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @landlord.last_name %>
</p>

<p>
  <strong>Telephone number:</strong>
  <%= @landlord.telephone_number %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @landlord.email_address %>
</p>

<p>
  <strong>Mailing address:</strong>
  <%= @landlord.mailing_address %>
</p>

<p>
  <strong>Date registered with us:</strong>
  <%= @landlord.date_registered_with_us %>
</p>

<%= link_to 'Edit', edit_landlord_path(@landlord) %> |
<%= link_to 'Back', landlords_path %>

app/views/listtype/displaylist.html.erb
<h1>Properties with matching work orders</h1>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Properties Admin Panel</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Work outstanding</th>
      <th>Landlord ID</th>
      <th>Work outstanding type</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.address %></td>
        <td><%= property.work_outstanding %></td>
        <td><%= property.landlord_id %></td>
        <td><%= property.work_outstanding_type %></td>
        <td><%= property.latitude %></td>
        <td><%= property.longitude %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<%stylesheet_link_tag 'show.css.scss'%>



<div class="container">
  <div class="row">
        <div class="col-md-3" id="leftCol">
                
        <div class="well" id="landlord"> 
                <ul class="nav nav-stacked" id="landlord-sidebar"><h3>Landlord Information</h3>
                </ul>
                <p>
                  <% if @property.landlord == nil %>
                    <strong>Property does not have registered Landlord yet!</strong>
                    <% else %>
                  <strong>Name:</strong><%= @property.landlord.first_name + ' ' + @property.landlord.last_name %></br>
                  <strong>Email:</strong><%= mail_to @property.landlord.email_address, @property.landlord.email_address %></br>
                  <strong>Tel:</strong><%= @property.landlord.telephone_number %></br>
                  <strong>Mailing Address:</strong><%=@property.landlord.mailing_address%></br>
                  <strong>Client Since:</strong><%=@property.landlord.date_registered_with_us %></br>
                </p>
                <% end %>
                
          </div>
        <div class="well" id="blank"> 
                <ul class="nav nav-stacked" id="middle-sidebar">
                </ul>
               
            
          </div>

        <div class="well" id="tenant"> 
                <ul class="nav nav-stacked" id="tenant-sidebar"><h3>Tenant Information</h3>
                </ul>
                <p>
                  <% if @property.tenant == nil %>
                    <strong>Property does not have registered Tenant yet!</strong>
                    <% else %>
                      <strong>Name:</strong><%= @property.tenant.first_name + ' ' + @property.tenant.last_name %></br>
                      <strong>Email:</strong><%= mail_to @property.tenant.email_address, @property.tenant.email_address %></br>
                      <strong>Tel:</strong><%= @property.tenant.telephone_number %></br>
                      <strong>Tenant Since:</strong><%=@property.tenant.date_of_commencement.to_formatted_s %></br>
                      <strong>Client Since:</strong><%=@property.landlord.date_registered_with_us.to_formatted_s %></br>
                  <% end %>
                </p>
          </div>
          </div>  
          <div class="col-md-9">
                <h2 id="sec0"><%= @property.address %></h2>
                
            
 
                
                
              
              <hr id="headerhr">
                         <div style='width: 800px;'>
                            <div id="map" style='width: 800px; height: 400px;'></div>
                          </div>
                <h2 id="sec1">Work Outstanding?</h2>

                <p>
                </p>
                <div class="row">
                  <div class="col-md-6">
                    <div class="panel panel-default">
                      <div class="panel-heading">

                        <% if @property.work_outstanding == true %>
                        <h3><%= "Yes!" %></h3>
                        <% else %>
                        <h3 id="noworkheader"><%= "No" %></h3>
                        <% end %>
                      </div>
                      <div class="panel-body">
                          <% if @property.work_outstanding == true %>
                      <h4><%= "A work order was raised for this property on: " + @property.updated_at.to_formatted_s(:long_ordinal) %></h4>
                      <p id="worktype"><%= @property.work_outstanding_type %></p>
                      <% else %>
                      <p><%= "Looks like there's nothing for you to organise on this property. Perhaps it's time for a cup of tea." %>
                      <% end %>
                      <%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', "/" %>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="panel panel-default">
                      <div class="panel-heading">

                      
                        <h3>Closest Nearby Properties</h3>
                      
                      </div>
                      <div class="panel-body">
                        <ul>
                        <% for property in @property.nearbys(10) %>
                        <li><%= link_to property.address, property %> (<%= property.distance.round(2) %> miles) </li>
                        <%end%>
                        </ul>
                      </div>
                    </div>
                  </div>
                  </div>  
                </div>
                      
              
                <hr>
                       
          </div> 
    </div>
</div>





<script type="text/javascript">
mapStyle = [{"featureType":"landscape","stylers":[{"color":"#6c8080"},{"visibility":"simplified"}]},{"featureType":"administrative","elementType":"labels.text","stylers":[{"visibility":"on"}]},{"featureType":"road","stylers":[{"visibility":"simplified"}]},{"featureType":"poi","stylers":[{"visibility":"on"}]},{"featureType":"road.highway","elementType":"labels","stylers":[{"visibility":"on"}]},{"featureType":"road.highway","elementType":"labels","stylers":[{"visibility":"on"}]},{"featureType":"road","elementType":"labels.icon","stylers":[{"visibility":"on"}]},{"featureType":"transit","elementType":"labels","stylers":[{"visibility":"on"}]},{"elementType":"labels","stylers":[{"visibility":"on"}]},{"featureType":"road.highway","stylers":[{"color":"#d98080"},{"hue":"#eeff00"},{"lightness":100},{"weight":1.5}]}]

handler = Gmaps.build('Google');
handler.buildMap({ provider: {styles: mapStyle}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @property_marker.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(15);
});
</script>

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render 'form' %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.erb
<h1>Listing tenants</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Telephone number</th>
      <th>Email address</th>
      <th>Date of commencement</th>
      <th>Date of termination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tenants.each do |tenant| %>
      <tr>
        <td><%= tenant.first_name %></td>
        <td><%= tenant.last_name %></td>
        <td><%= tenant.telephone_number %></td>
        <td><%= tenant.email_address %></td>
        <td><%= tenant.date_of_commencement %></td>
        <td><%= tenant.date_of_termination %></td>
        <td><%= link_to 'Show', tenant %></td>
        <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
        <td><%= link_to 'Destroy', tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tenant', new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New tenant</h1>

<%= render 'form' %>

<%= link_to 'Back', tenants_path %>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @tenant.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @tenant.last_name %>
</p>

<p>
  <strong>Telephone number:</strong>
  <%= @tenant.telephone_number %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @tenant.email_address %>
</p>

<p>
  <strong>Date of commencement:</strong>
  <%= @tenant.date_of_commencement %>
</p>

<p>
  <strong>Date of termination:</strong>
  <%= @tenant.date_of_termination %>
</p>

<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>

app/views/welcome/index.html.erb
<%stylesheet_link_tag 'styles.css.scss'%>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


<div class="container-fluid" id="main">
  <div class="row">
    <div class="col-xs-8" id="left">

    <h1>Property Pilot Management System</h1>
      
      <!-- item list -->
      
      
      <hr>


      <!-- DataTable Rows -->
    <table id="property_list" class="stripe hover" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Address</th>
                <th>Work Outstanding</th>
                <th>Work Outstanding Type</th>
                <th>Landlord Name</th>

            </tr>
        </thead>
 
        <tfoot>
            <tr>
                <th>ID</th>
                <th>Address</th>
                <th>Work Outstanding</th>
                <th>Work Outstanding Type</th>
                <th>Landlord Name</th>
            </tr>
        </tfoot>
        <tbody>
        <!-- Populate DataTable -->
        <% @properties.each do |prop| %>
       
            <tr>
                <td><%= prop.id %></td>
                <td><%=link_to prop.address, property_path(prop) %></td>
                <% if prop.work_outstanding == true %>
                <td><%="Yes" %></td>
                <% else %>
                <td><%="No" %></td>
                <% end %>
                <td><%= prop.work_outstanding_type %></td>
                <td><%= prop.landlord.first_name + ' ' + prop.landlord.last_name %></td>
            </tr>
        <% end %>

        </tbody>
    </table>


      <hr>
          </div>
        <div class="col-xs-4" id="map"></div>
    </div>
  </div>

</div>


<script type="text/javascript">

mapStyle =
[{"featureType":"water","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":17}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":17}]},{"featureType":"road.highway","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":29},{"weight":0.2}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":18}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":16}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":21}]},{"elementType":"labels.text.stroke","stylers":[{"visibility":"on"},{"color":"#000000"},{"lightness":16}]},{"elementType":"labels.text.fill","stylers":[{"saturation":36},{"color":"#000000"},{"lightness":40}]},{"elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"geometry","stylers":[{"color":"#000000"},{"lightness":19}]},{"featureType":"administrative","elementType":"geometry.fill","stylers":[{"color":"#000000"},{"lightness":20}]},{"featureType":"administrative","elementType":"geometry.stroke","stylers":[{"color":"#000000"},{"lightness":17},{"weight":1.2}]}]
handler = Gmaps.build('Google');
handler.buildMap({
  provider: {styles: mapStyle},
  internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @all_property_markers.to_json %>);
  console.log(<%=raw @all_property_markers.to_json %>);
  console.log(markers);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(12);

});
</script> 


<%javascript_include_tag 'datatables.js' %>


<%= stylesheet_link_tag 'jquery.dataTables.css' %>

<%= javascript_include_tag 'jquery.dataTables.min.js' %>

app/views/welcome/worklist.html.erb
<h1>Properties with <%= @type %> work orders</h1>
<p>
	
	<% @list.each do |p| %>
	 <%=link_to p.address, 'worklist/' + p.id.to_s %></br>
	<% end %>
	